### ISSUE TITLE
Screenshot / video

### ISSUE THREAD

**Issue by rmehta** [mxmo-co/title_links#1]
@MaxMorais will be great if you can add a screenshot / video in README so that we can see what this app does!

**Comment by MaxMorais** [comment]
@rmehta I'll provide it in the Weekend! Thanks!

**Comment by mhbu50** [comment]
+1

**Comment by MaxMorais** [comment]
@rmehta, @mhbu50 fixed via https://github.com/mxmo-co/title_links/blob/dbe2d5c4cd5e7a17fce992fa0a08bfd454223d8c/README.md

**Comment by rmehta** [comment]
You might want to update it for v8, do you think it would make sense as a core feature in Frappe?

**Comment by MaxMorais** [comment]
@rmehta I think is very early to think in a merge, have various issues that need to be fixed!

Some of they are reported in #6, it will require more some hacks in other pieces of frappe, and a bit of rethink about how to store and get the value of a title link, without use "$input.val()"

**Comment by joezsweet** [comment]
Would be nice to have something like: 

https://select2.github.io/examples.html#single
