### ISSUE TITLE
Can't get this to work...

### ISSUE THREAD

**Issue by joshreeder** [mxmo-co/title_links#11]
<img width="857" alt="screen shot 2017-12-07 at 11 29 43 am" src="https://user-images.githubusercontent.com/2237329/33729007-f90359d0-db41-11e7-95b4-c3ad1540a9fe.png">
<img width="417" alt="screen shot 2017-12-07 at 11 29 30 am" src="https://user-images.githubusercontent.com/2237329/33729008-f91258cc-db41-11e7-8216-d6e44993a901.png">

have tried restarting everything - it shows the name in both the top and bottom of the search...

Uninstalling the app only removes the name from the second row. 

Please help.

**Comment by MaxMorais** [comment]
@joshreeder what is the version that you are using of frappe

**Comment by joshreeder** [comment]
Current version

**Comment by GSLabIt** [comment]
@joshreeder actually it's the only way found to have title_links working 😢

**Comment by joshreeder** [comment]
To be clear on your response, you are saying that the app is no longer working in the current version of Frappe and there is no way to fix it?

To be clear, the app should: 
1. Use the **Doctype** "Title" field for the **Search Result** "Title" line
2. Use the **Doctype** "Name" field in the **Search Results** "Description" line

Currently these things are not happening. 

What is happening is that with the app on, the Entry Name is still used in title area and also added to the description area.

**Comment by GSLabIt** [comment]
The app is working ..when you select a value, it shows you the title_name of the selected name. It won't work in Awesome widget as you want it to be ..it needs lot of over heads to make it work. Feel free to send a PR for that 😉

**Comment by joshreeder** [comment]
Sorry, but I am confused. You say its working as it is described in the read me. But I can not get it to function. 

Where is it working exactly for you? I am expecting it to work in a doctype "link" form field.

Mine still shows the name (HA0001), not the title (Pool 5).

Is awesome widget the search field at the top?

**Comment by GSLabIt** [comment]
have a look at this, on version Frappe Framework: v9.2.23 (master): 

![yyfk9mnqwn](https://user-images.githubusercontent.com/11652845/33955545-363a4ae4-e03c-11e7-9acd-bb83e203322f.gif)

**Comment by joshreeder** [comment]
oh ok - I get it now... Thank you for the clarification!

**Comment by joshreeder** [comment]
@MaxMorais hey bro, contact me, need help with a ERPnext project. josh@whoagency.com
