### ISSUE TITLE
[ERPNext - V7] Error enabling require list_item_main.html

### ISSUE THREAD

**Issue by joezsweet** [mxmo-co/title_links#2]
When enabling:

`frappe.require('assets/title_links/templates/list_item_main.html');`

Rise error:

`TypeError: callback is not a function. (In 'callback()', 'callback' is undefined`

in:

`/home/frappe/frappe-bench/apps/frappe/frappe/public/js/frappe/assets.js`

**Comment by MaxMorais** [comment]
@joezsweet this is because the new behavior of assets in frappe that is async!

I'm not using the v7 for now!

**Comment by joezsweet** [comment]
..when u r going to move on V7? :)

**Comment by MaxMorais** [comment]
@joezsweet I'll take some months to do it

**Comment by joezsweet** [comment]
ok, in the mean while i'll have a better knowledge of frappe / erpnext and would help on this ..or even better would be merged into erpnext by the team.

**Comment by MaxMorais** [comment]
@joezsweet Fixed

**Comment by joezsweet** [comment]
Great! Thx.

Are you going to add a pull request to frappe?

**Comment by MaxMorais** [comment]
@joezsweet no plans for that!
