### ISSUE TITLE
[ERPNext - V7] Some DocType showing code instead of title 

### ISSUE THREAD

**Issue by joezsweet** [mxmo-co/title_links#3]
Please have a look at 

https://discuss.erpnext.com/t/frappe-hack-links-using-related-title-instead-of-name/13838/62?u=joez

For detailed error and screenshots.

**Comment by MaxMorais** [comment]
@joezsweet this is because the new design of v7!

**Comment by joezsweet** [comment]
..when u r going to move on V7? :)

**Comment by MaxMorais** [comment]
@joezsweet Fixed
