### ISSUE TITLE
Showing title_name as search field in drop box window

### ISSUE THREAD

**Issue by joezsweet** [mxmo-co/title_links#5]
@MaxMorais please look at the following:

i've defined item_category_name in `title` and`search fields`

<img width="1209" alt="schermata 2017-02-08 alle 12 34 19" src="https://cloud.githubusercontent.com/assets/11652845/22735737/54096ca0-edfb-11e6-9746-9cbbf9f0aa9d.png">

but it not appear in drop down box:

<img width="527" alt="schermata 2017-02-08 alle 12 34 55" src="https://cloud.githubusercontent.com/assets/11652845/22735736/53fc92d2-edfb-11e6-98e5-c3e799e1d5c8.png">

I'd like to have this: 

<img width="522" alt="schermata 2017-02-08 alle 10 18 45" src="https://cloud.githubusercontent.com/assets/11652845/22735773/819f5116-edfb-11e6-99a5-743d74fb8f71.png">

**Comment by MaxMorais** [comment]
@joezsweet can you get me a screenshot of your `Item Category Code` Doctype?

**Comment by joezsweet** [comment]
it's the first pic

**Comment by MaxMorais** [comment]
@joezsweet I mean a screenshot of one record in your `Item Category`

**Comment by joezsweet** [comment]
@MaxMorais here it comes ..

<img width="1216" alt="schermata 2017-02-08 alle 12 49 27" src="https://cloud.githubusercontent.com/assets/11652845/22736142/1abc4e8e-edfd-11e6-92b8-78ad41242f43.png">

**Comment by MaxMorais** [comment]
@joezsweet sounds that it's not working property for you, because instead of Display "C-011" it should display "PESCHERIA", do you run `bench build`?

**Comment by joezsweet** [comment]
Yes i do ...i'll rebuild and let you know

**Comment by MaxMorais** [comment]
Ok

**Comment by joezsweet** [comment]
no way ..same result :(

**Comment by MaxMorais** [comment]
@joezsweet maybe you need to clear the cache or something like, because you are getting the same behavior with the app installed and the app not installed (that is the default link behavior)

What is the value returned by:

```
bench console
>>> frappe.get_installed_apps()
```
?

**Comment by joezsweet** [comment]
i've cleared cache, the result is

```
In [1]: frappe.get_installed_apps()
Out[1]:
[u'frappe',
 u'erpnext',
 u'istorecast',
 u'istorecast_ceu',
 u'istorecast_lkd',
 u'istorecast_delta',
 u'istorecast_isa',
 u'title_links']
```

**Comment by MaxMorais** [comment]
Very weird! The behavior is like the app is not installed to you! I don't have idea about what can be, but you should not get **C-011** in the display of your links, but **PESCHERIA** that is the `title_field`

**Comment by joezsweet** [comment]
I'm on:

ERPNext: v7.2.19
Frappe Framework: v7.2.15

I've added a new field to search fields, now i have: 

`category_code, category_name, naming_series`

and actually i'm getting: 

<img width="455" alt="schermata 2017-02-08 alle 13 31 23" src="https://cloud.githubusercontent.com/assets/11652845/22737344/fba13bb2-ee02-11e6-9c54-dd8a0e20d3d4.png">

modifying to: `category_name, naming_series, category_code`  i get:

<img width="452" alt="schermata 2017-02-08 alle 13 33 56" src="https://cloud.githubusercontent.com/assets/11652845/22737429/4c7bdf24-ee03-11e6-8c3e-d8e7b6cf82a8.png">

It seems it' cutting the last field in the sequence

**Comment by MaxMorais** [comment]
Let me check the Widget JS

**Comment by MaxMorais** [comment]
@joezsweet in the newer versions autocomplete was replaced to awesomplete, I need fix this!

**Comment by joezsweet** [comment]
k, thx

**Comment by MaxMorais** [comment]
@joezsweet fixed! Try now and let me know if it works fine to you!

**Comment by joezsweet** [comment]
Search fields: category_name, category_code

<img width="446" alt="schermata 2017-02-08 alle 15 21 23" src="https://cloud.githubusercontent.com/assets/11652845/22741109/55f64594-ee12-11e6-8f7f-f724ef8d4b8c.png">

Search fields:  category_code, category_name

<img width="459" alt="schermata 2017-02-08 alle 15 23 25" src="https://cloud.githubusercontent.com/assets/11652845/22741209/a4fdb76c-ee12-11e6-9dd0-42ca78d8602e.png">



Still cutting the last one in this case ..applied `bench build, bench clear-cache`

**Comment by MaxMorais** [comment]
@joezsweet, I'm unable to replicate!

**Comment by MaxMorais** [comment]
Did you tryied to restart the bench or supervisor?

**Comment by joezsweet** [comment]
wait a sec ..i'll switch off VM and restart ..

**Comment by joezsweet** [comment]
Restarted VM, bench clear-cache, bench-build, bench start ...no way :(

**Comment by MaxMorais** [comment]
@joezsweet any chance to share scree, like TeamViewer or Screenhero? you can pingme in PVT on gitter.im

**Comment by joezsweet** [comment]
TeamViewer

**Comment by MaxMorais** [comment]
Fixed via pair session with @joezsweet on TeamViewer

**Comment by MaxMorais** [comment]
@joezsweet can you post the final screenshot?

**Comment by joezsweet** [comment]
Yes, i am going to post. 

There is  a really small thing to change, if possible; show the search widget right when field is clicked, actually it's shown only if space or any char is typed. It works like that in original function.

**Comment by joezsweet** [comment]
here it comes ..

<img width="460" alt="schermata 2017-02-08 alle 17 00 56" src="https://cloud.githubusercontent.com/assets/11652845/22747130/6967474a-ee26-11e6-9231-5ccaeb1dc904.png">

**Comment by MaxMorais** [comment]
<img width="1182" alt="schermata-2017-02-08-alle-18 31 28" src="https://cloud.githubusercontent.com/assets/1288676/22749635/2d6f43a2-ee15-11e6-80c0-d6fbb968a26b.png">

**Comment by MaxMorais** [comment]
<img width="501" alt="schermata-2017-02-08-alle-18 46 33" src="https://cloud.githubusercontent.com/assets/1288676/22749913/12713eb0-ee16-11e6-87e3-0fd4770ea9a2.png">
